### ISSUE TITLE
Use a .sublime-project file

### ISSUE THREAD

**Issue by shirhatti** [ligershark/Kulture#13]
Using a .sublime-project similar to a .sln as employed by Visual Studio would make it easier to store project specific settings without modifying the global package settings.
### Pros

Easier to store project-specific settings
Handle multiple projects
No more `project.json` not found bugs
### Cons

Stores a extra file on disk that you need to check-in into Source Control.
This file will be useless to most folks using Visual Studio

**Comment by jchannon** [comment]
I added a requirement for `.sublime-project` here to get intellisense working https://github.com/moonrabbit/OmniSharpSublime/pull/5/files

**Comment by sayedihashimi** [comment]
@jchannon What content is required to go into the .sublime-project file?

**Comment by jchannon** [comment]
This link explains it but at the minimum just a path to the folder where all the files are. You can then exclude sub folders or file types `*.sln` :wink: 

http://www.sublimetext.com/docs/3/projects.html

**Comment by sayedihashimi** [comment]
OK I have made the changes in commit 0a09e6e54a42992cd0e19da56f7e58257bd855a3. I created a wiki page to describe how it works https://github.com/ligershark/Kulture/wiki/How-does-Kulture-look-locate-project.json. Please check it out and if possible try it out.

Do we need any updates here?

I'll close this item now because I think it's been addressed, but please re-open it if that's not the case.
